const getters = {
  // app
  adminLeftMenu: state => state.leftMenu.adminMenu,
  isCollapsed: state => state.app.isCollapsed,
  breadCrumbs: state => state.app.breadCrumbs,
  messageObject: state => state.app.messageObject,
  page: state => state.page.page,
  per_page: state => state.page.per_page,
  total: state => state.page.total,
  pageSizes: state => state.page.pageSizes,
  superAdminLeftMenu: state => state.leftMenu.superAdminMenu,
  userLeftMenu: state => state.leftMenu.userMenu,
  // super_admin
  dasboardCustomers: state => state.dashboard.dasboardCustomers,
  dasboardBookings: state => state.dashboard.dasboardBookings,
  dasboardRevenues: state => state.dashboard.dasboardRevenues,
  chartDataBookingsNew: state => state.dashboard.chartDataBookingsNew,
  chartDataBookingsCompleted: state => state.dashboard.chartDataBookingsCompleted,
  chartDataBookingsCanceld: state => state.dashboard.chartDataBookingsCanceld,
  chartDataRevenues: state => state.dashboard.chartDataRevenues,
  dataChart: state => state.dashboard.dataChart,
  totalNew: state => state.dashboard.totalNew,
  totalCompleted: state => state.dashboard.totalCompleted,
  totalCancel: state => state.dashboard.totalCancel,
  totalRevenues: state => state.dashboard.totalRevenues,

  visibleService: state => state.service.visibleService,
  visibleBooking: state => state.service.visibleBooking,
  services: state => state.service.services,
  editService: state => state.service.editService,
  serviceRules: state => state.service.serviceRules,
  serviceIsEdit: state => state.service.serviceIsEdit,
  bookings: state => state.booking.bookings,

  newBarber: state => state.barber.newBarber,
  visibleBarber: state => state.barber.visibleBarber,
  editBarber: state => state.barber.editBarber,
  barbers: state => state.barber.barbers,
  barberIsEdit: state => state.barber.barberIsEdit,
  barberRules: state => state.barber.barberRules,

  visibleServiceCharge: state => state.serviceCharge.visibleServiceCharge,
  serviceCharges: state => state.serviceCharge.serviceCharges,
  editServiceCharge: state => state.serviceCharge.editServiceCharge,
  serviceChargeRules: state => state.serviceCharge.serviceChargeRules,
  serviceChargeIsEdit: state => state.serviceCharge.serviceChargeIsEdit,
  // admin
  editAdmin: state => state.admin.editAdmin,
  // user
  editUser: state => state.user.editUser,
  prefectures: state => state.location.prefectures,
  cities: state => state.location.cities,
  communes: state => state.location.communes,
  barbersFront: state => state.barber.barbersFront,
  servicesFront: state => state.service.servicesFront,
  frontServiceCharges: state => state.serviceCharge.frontServiceCharges,
  visibleModalTablePrice: state => state.barber.visibleModalTablePrice,
  editBooking: state => state.booking.editBooking,
  bookingIsEdit: state => state.booking.bookingIsEdit,
  visibleModalBooking: state => state.booking.visibleModalBooking,
  bookingRules: state => state.booking.bookingRules,
}
export default getters
